// Code generated by protoc-gen-go. DO NOT EDIT.
// source: geometry.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Dimensions struct {
	Shape                string   `protobuf:"bytes,1,opt,name=shape,proto3" json:"shape,omitempty"`
	Unit                 string   `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Dimension            []int32  `protobuf:"varint,3,rep,packed,name=dimension,proto3" json:"dimension,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dimensions) Reset()         { *m = Dimensions{} }
func (m *Dimensions) String() string { return proto.CompactTextString(m) }
func (*Dimensions) ProtoMessage()    {}
func (*Dimensions) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b03e188c3a7128a, []int{0}
}

func (m *Dimensions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dimensions.Unmarshal(m, b)
}
func (m *Dimensions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dimensions.Marshal(b, m, deterministic)
}
func (m *Dimensions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dimensions.Merge(m, src)
}
func (m *Dimensions) XXX_Size() int {
	return xxx_messageInfo_Dimensions.Size(m)
}
func (m *Dimensions) XXX_DiscardUnknown() {
	xxx_messageInfo_Dimensions.DiscardUnknown(m)
}

var xxx_messageInfo_Dimensions proto.InternalMessageInfo

func (m *Dimensions) GetShape() string {
	if m != nil {
		return m.Shape
	}
	return ""
}

func (m *Dimensions) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *Dimensions) GetDimension() []int32 {
	if m != nil {
		return m.Dimension
	}
	return nil
}

type Area struct {
	Area                 float32  `protobuf:"fixed32,1,opt,name=area,proto3" json:"area,omitempty"`
	Formula              string   `protobuf:"bytes,2,opt,name=formula,proto3" json:"formula,omitempty"`
	Unit                 string   `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Area) Reset()         { *m = Area{} }
func (m *Area) String() string { return proto.CompactTextString(m) }
func (*Area) ProtoMessage()    {}
func (*Area) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b03e188c3a7128a, []int{1}
}

func (m *Area) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Area.Unmarshal(m, b)
}
func (m *Area) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Area.Marshal(b, m, deterministic)
}
func (m *Area) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Area.Merge(m, src)
}
func (m *Area) XXX_Size() int {
	return xxx_messageInfo_Area.Size(m)
}
func (m *Area) XXX_DiscardUnknown() {
	xxx_messageInfo_Area.DiscardUnknown(m)
}

var xxx_messageInfo_Area proto.InternalMessageInfo

func (m *Area) GetArea() float32 {
	if m != nil {
		return m.Area
	}
	return 0
}

func (m *Area) GetFormula() string {
	if m != nil {
		return m.Formula
	}
	return ""
}

func (m *Area) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func init() {
	proto.RegisterType((*Dimensions)(nil), "rce.Dimensions")
	proto.RegisterType((*Area)(nil), "rce.Area")
}

func init() { proto.RegisterFile("geometry.proto", fileDescriptor_0b03e188c3a7128a) }

var fileDescriptor_0b03e188c3a7128a = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x4f, 0xbb, 0x0e, 0x82, 0x40,
	0x10, 0x14, 0x0e, 0x44, 0xb6, 0xd0, 0xe4, 0x62, 0x71, 0x31, 0x16, 0x84, 0x46, 0x2a, 0x0a, 0xf9,
	0x02, 0x13, 0x13, 0xac, 0x89, 0x3f, 0x70, 0xe2, 0xaa, 0x24, 0xc2, 0x91, 0xe5, 0x28, 0xfc, 0x7b,
	0xc3, 0x0a, 0xd2, 0xcd, 0xcc, 0x66, 0x1e, 0x0b, 0xeb, 0x27, 0x9a, 0x1a, 0x2d, 0x7d, 0xd2, 0x96,
	0x8c, 0x35, 0x52, 0x50, 0x89, 0xf1, 0x15, 0xe0, 0x5c, 0xd5, 0xd8, 0x74, 0x95, 0x69, 0x3a, 0xb9,
	0x05, 0xbf, 0x7b, 0xe9, 0x16, 0x95, 0x13, 0x39, 0x49, 0x58, 0xfc, 0x88, 0x94, 0xe0, 0xf5, 0x4d,
	0x65, 0x95, 0xcb, 0x22, 0x63, 0xb9, 0x87, 0xf0, 0x3e, 0xf9, 0x94, 0x88, 0x44, 0xe2, 0x17, 0xb3,
	0x10, 0x5f, 0xc0, 0x3b, 0x11, 0xea, 0xc1, 0xa9, 0x09, 0x35, 0xc7, 0xb9, 0x05, 0x63, 0xa9, 0x20,
	0x78, 0x18, 0xaa, 0xfb, 0xb7, 0x1e, 0x03, 0x27, 0xfa, 0xef, 0x11, 0x73, 0xcf, 0x31, 0x83, 0x55,
	0x3e, 0xce, 0x96, 0x07, 0x08, 0x72, 0xb4, 0x1c, 0xbc, 0x49, 0xa9, 0xc4, 0x74, 0x5e, 0xbe, 0x0b,
	0x59, 0x18, 0x6e, 0xf1, 0xe2, 0xb6, 0xe4, 0x07, 0xb3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd0,
	0x29, 0x37, 0x77, 0xf2, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GeometryClient is the client API for Geometry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GeometryClient interface {
	GetArea(ctx context.Context, in *Dimensions, opts ...grpc.CallOption) (*Area, error)
}

type geometryClient struct {
	cc *grpc.ClientConn
}

func NewGeometryClient(cc *grpc.ClientConn) GeometryClient {
	return &geometryClient{cc}
}

func (c *geometryClient) GetArea(ctx context.Context, in *Dimensions, opts ...grpc.CallOption) (*Area, error) {
	out := new(Area)
	err := c.cc.Invoke(ctx, "/rce.Geometry/GetArea", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeometryServer is the server API for Geometry service.
type GeometryServer interface {
	GetArea(context.Context, *Dimensions) (*Area, error)
}

// UnimplementedGeometryServer can be embedded to have forward compatible implementations.
type UnimplementedGeometryServer struct {
}

func (*UnimplementedGeometryServer) GetArea(ctx context.Context, req *Dimensions) (*Area, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArea not implemented")
}

func RegisterGeometryServer(s *grpc.Server, srv GeometryServer) {
	s.RegisterService(&_Geometry_serviceDesc, srv)
}

func _Geometry_GetArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Dimensions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeometryServer).GetArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rce.Geometry/GetArea",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeometryServer).GetArea(ctx, req.(*Dimensions))
	}
	return interceptor(ctx, in, info, handler)
}

var _Geometry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rce.Geometry",
	HandlerType: (*GeometryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArea",
			Handler:    _Geometry_GetArea_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "geometry.proto",
}
